default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: case_management_development

test:
  <<: *default
  database: case_management_test

production:
  <<: *default
  database: case_management_production
  username: <%= ENV["PG_PRODUCTION_USER"] %>
  password: <%= ENV["PG_PRODUCTION_PASSWORD"] %>
  host: <%= ENV["PG_PRODUCTION_HOST"] %>
